[info]
relay_url = "wss://nostr-rs-relay-production-1569.up.railway.app"
name = "11x LOVE Private Relay"
description = "Private relay for the 11x LOVE coaching community"
pubkey = "3d70ec1ea586650a0474d6858454209d222158f4079e8db806f017ef5e30e767"
contact = "npub184cwc849sejs5pr566zcg4pqn53zzk85q70gmwqx7qt77h3suansvet30s"

[database]
data_directory = "/data"

[network]
port = 8080
address = "0.0.0.0"

[limits]
messages_per_sec = 100
max_event_bytes = 131072
max_ws_message_bytes = 524288
max_conn = 128

[authorization]
pubkey_whitelist = [
    "3d70ec1ea586650a0474d6858454209d222158f4079e8db806f017ef5e30e767"
]

[verified_users]
mode = "whitelist"
pubkey_whitelist = [
    "3d70ec1ea586650a0474d6858454209d222158f4079e8db806f017ef5e30e767"
]

[options]
reject_future_seconds = 1800
